@startuml
title Flow - Forgot Password

participant User
participant App
participant Server
== Send Email ==
User -> App: Send the email
App -> Server: Send the User's Email
== Authentication ==
Server -> User: Send a authentication code through gmail
User -> App: Fill the authentication code\nto authenticate
App -> Server: Verify the authentication code
Server -> Server: Reset Password of User
App <- Server: Wait for new Password
== ReSet Password ==
User -> App: |**Type**|**Info**|\n|**Password **| 6 - 25 characters |\n|**Pre-Password **| 6 - 25 characters |

group Send New Password
  App -> Server:
  App <- Server:
end
User <- App: Forgot Password successfully
@enduml