@startuml
title Flow - Change Password

participant User
participant App
participant Server
== Send New Password ==
User -> App: Request to update new password \n|**Type**|**Info**|\n|**Old Password **| 6 - 25 characters |\n|**New Password **| 6 - 25 characters |\n|**Pre-New Password **| 6 - 25 characters |
App -> Server: Send Change Password Request
== Wait for Response ==
Server -> App: Response for request
User <- App: Update success for User
@enduml